### ISSUE TITLE
38-rust-lua-nvim.md instructions don't work as specified on MacOs

### ISSUE THREAD

**Issue by zdcthomas** [kdheepak/blog#7]
Hello! First off, I want to say that I love the blog post! It's such an exciting way to write plugins and I had no idea about the lua C abi bindings in such detail before. I have run into a bit of a snag though it's probably just due to my own ignorance. 

I'm running MacOs 10.15.7, and after following the instructions I wasn't able to get the plugin to compile. 
My steps were
1. `cargo new --lib rust_plugin_test`
2. add 
```
[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = {version = "*", features = ["luajit", "vendored", "module", "macros"]}
```
 to my cargo.toml
3. Replace my src/lib.rs with 
```
use mlua::chunk;
use mlua::prelude::*;

fn hello(lua: &Lua, name: String) -> LuaResult<LuaTable> {
    let t = lua.create_table()?;
    t.set("name", name.clone())?;
    let _globals = lua.globals();
    lua.load(chunk! {
        print("hello, " .. $name)
    })
    .exec()?;
    Ok(t)
}

#[mlua::lua_module]
fn moonshine(lua: &Lua) -> LuaResult<LuaTable> {
    let exports = lua.create_table()?;
    exports.set("hello", lua.create_function(hello)?)?;
    Ok(exports)
}

``` 
4. Since there is no `~/.cargo/config`  file by default I `touch .cargo/config`
5. copy 
```
[target.x86_64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-apple-darwin]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
``` 
into `~/.cargo/config`
6. Finally I run `cargo build --release && mv target/release/libmoonshine.dylib lua/moonshine.so`
The output of which is 
```
mv: rename target/release/libmoonshine.dylib to lua/moonshine.so: No such file or directory
```

I'm sure I'm missing something obvious, and if I am I'm very sorry. 

Thanks again for your time!

**Comment by kdheepak** [comment]
What is the output of `cargo build --release`?

**Comment by zdcthomas** [comment]
Nevermind! I realized it was completely my bad! Very sorry for wasting your time, I had a misnaming that I didn't catch until just now! 
Thanks Again!

**Comment by kdheepak** [comment]
Great that you figured it out!
